from random import choice
import string
import pyperclip


class Credentials:
        """
        This class generates instances of a user's credentials
         """

        user_credential_list = []

        def __init__(self, user_account, user_name, password):
            """
            This method defines the credentials that have been entered by the user to be stored
            """

            self.user_account = user_account
            self.user_name = user_name
            self.password = password

        def save_credentials(self):
            Credentials.user_credential_list.append(self)
            """
            This method is to store a new set of credentials entered by a user by adding them to the 
            user_credential_list
            """

        def delete_user_credentials(self):
            """
            A method that removes user credentials from the user_credential_list
            """
            Credentials.user_credential_list.remove(self)



        @classmethod
        def credentials_available(cls, user_account):
            """
            This method checks whether credentials for the user_account details entered exists in the 
            user_credential_list
            """
            for credential in cls.user_credential_list:
                if credential.user_account == user_account:
                    return True
            return False

    
        @classmethod 
        def access_credentials(cls, password):
            """
            This method helps user find their credentials by taking in a user's user_account name
            and returns the credential details that matches the user_account name entered
            """

            user_credential_list = []

            for credential in cls.user_credential_list:
                if credential.password == password:
                    user_credential_list.append(credential)
                
            return user_credential_list

        @classmethod
        def display_user_credentials(cls,):
            """
            This method will return all the credential details of the user from the user_credential_list
            """
            return cls.user_credential_list

        @classmethod
        def copy_password(cls, user_account):
            """
            A method that will help copy password into the clipboard using pyperclip
            """
            my_credentials = Credentials.display_user_credentials(user_account)
            pyperclip.copy(my_credentials.password)



        @classmethod
        def passwordGenerator(cls):
            """
            This method will create/generate a new random 8-character password consisting of a string of digits,
            letters and special characters
            """

            size = 8

            alphanum = string.ascii_lowercase + string.ascii_uppercase + string.digits

            generated_password = ''.join(choice(alphanum) for num in range(size))

            return generated_password

            

        def enter_user_password():
            """
            Method will allow user to input passwords of their choice if they are not interested in the autogenerated 
            password
            """

            password = input(string.ascii_lowercase + string.ascii_uppercase + string.digits + "!@#$%^&*" + len>=8)
            if password == password:
                return True
            return False
